### ISSUE TITLE
Replace placeholder categories on the category filter navigation

### ISSUE THREAD

**Issue by andygott** [EMT/see-do#1]
The `$categories` variable has all categories.

**Comment by hparton** [comment]
`$categories` returns:
`{"3":"Exhibitions","5":"Films","2":"Gigs","4":"Hackdays & Workshops","1":"Talks"}` 

Shouldn't this return something similar to the `$events` variable:
`{"id":1,"title":"Northern Soul: The Film"...}`

Trying to do a foreach loop with a link to each category, like on the categories index page, produces this error because it doesn't have the slug:
`Trying to get property of non-object`

**Comment by andygott** [comment]
And it wasn’t available on every page. Fixed now: within the `common/nav.blade.php` view, `$categories` is always the full collection.
